<?php

declare(strict_types=1);

namespace Dirthara\Schema\Tests\Grammar;

use Dirthara\Schema\Table;
use PHPUnit\Framework\TestCase;
use Dirthara\Schema\Column\ColumnType;
use PHPUnit\Framework\Attributes\Test;
use PHPUnit\Framework\Attributes\DataProvider;
use Dirthara\Schema\Constraint\ReferentialAction;
use Dirthara\Schema\Grammar\PostgresSqlSchemaGrammar;
use Dirthara\Schema\Exceptions\InvalidSchemaException;

use function sprintf;

final class PostgresSqlSchemaGrammarTest extends TestCase
{
    private PostgresSqlSchemaGrammar $grammar;

    protected function setUp(): void
    {
        parent::setUp();

        $this->grammar = new PostgresSqlSchemaGrammar();
    }

    /**
     * @return list<string>
     */
    private function create(Table $table, bool $ifNotExists = false): array
    {
        return $this->grammar->compileCreate($table, $ifNotExists)->queries;
    }

    /**
     * @return list<string>
     */
    private function alter(Table $table): array
    {
        return $this->grammar->compileAlter($table)->queries;
    }

    #[Test]
    public function it_quotes_with_double_quotes(): void
    {
        $table = new Table('users');
        $table->string('email', 120);

        self::assertSame(['CREATE TABLE "users" ("email" VARCHAR(120) NOT NULL)'], $this->create($table));
    }

    #[Test]
    public function it_compiles_a_create_if_not_exists(): void
    {
        $table = new Table('users');
        $table->text('body');

        self::assertSame(['CREATE TABLE IF NOT EXISTS "users" ("body" TEXT NOT NULL)'], $this->create($table, true));
    }

    #[Test]
    public function it_generates_the_key_as_an_identity_column(): void
    {
        $table = new Table('users');
        $table->id();

        self::assertSame(
            [
                'CREATE TABLE "users" ("id" BIGINT NOT NULL GENERATED BY DEFAULT AS IDENTITY, '
                    . 'CONSTRAINT "users_primary" PRIMARY KEY ("id"))',
            ],
            $this->create($table),
        );
    }

    #[Test]
    public function it_drops_the_unsigned_modifier(): void
    {
        $table = new Table('users');
        $table->integer('score')->unsigned();

        self::assertSame(['CREATE TABLE "users" ("score" INTEGER NOT NULL)'], $this->create($table));
    }

    /**
     * @return iterable<string, array{ColumnType, string}>
     */
    public static function types(): iterable
    {
        yield 'boolean' => [ColumnType::Boolean, 'BOOLEAN'];
        yield 'tiny integer' => [ColumnType::TinyInteger, 'SMALLINT'];
        yield 'small integer' => [ColumnType::SmallInteger, 'SMALLINT'];
        yield 'integer' => [ColumnType::Integer, 'INTEGER'];
        yield 'big integer' => [ColumnType::BigInteger, 'BIGINT'];
        yield 'float' => [ColumnType::Float, 'REAL'];
        yield 'double' => [ColumnType::Double, 'DOUBLE PRECISION'];
        yield 'text' => [ColumnType::Text, 'TEXT'];
        yield 'json' => [ColumnType::Json, 'JSONB'];
        yield 'date' => [ColumnType::Date, 'DATE'];
        yield 'time' => [ColumnType::Time, 'TIME'];
        yield 'date time' => [ColumnType::DateTime, 'TIMESTAMP'];
        yield 'timestamp' => [ColumnType::Timestamp, 'TIMESTAMP'];
        yield 'uuid' => [ColumnType::Uuid, 'UUID'];
        yield 'binary' => [ColumnType::Binary, 'BYTEA'];
        yield 'decimal' => [ColumnType::Decimal, 'NUMERIC(8, 2)'];
    }

    #[Test]
    #[DataProvider('types')]
    public function it_maps_a_type(ColumnType $type, string $expected): void
    {
        $table = new Table('users');
        $table->column('value', $type);

        self::assertSame([sprintf('CREATE TABLE "users" ("value" %s NOT NULL)', $expected)], $this->create($table));
    }

    /**
     * @return iterable<string, array{bool, string}>
     */
    public static function booleans(): iterable
    {
        yield 'true' => [true, 'TRUE'];
        yield 'false' => [false, 'FALSE'];
    }

    #[Test]
    #[DataProvider('booleans')]
    public function it_writes_a_boolean_default_as_a_keyword(bool $default, string $expected): void
    {
        $table = new Table('users');
        $table->boolean('active')->default($default);

        self::assertSame(
            [sprintf('CREATE TABLE "users" ("active" BOOLEAN NOT NULL DEFAULT %s)', $expected)],
            $this->create($table),
        );
    }

    #[Test]
    public function it_leaves_a_backslash_alone(): void
    {
        $table = new Table('users');
        $table->string('status', 40)->default("O'Brien\\");

        self::assertSame(
            ['CREATE TABLE "users" ("status" VARCHAR(40) NOT NULL DEFAULT \'O\'\'Brien\\\')'],
            $this->create($table),
        );
    }

    #[Test]
    public function it_reports_postgres_when_a_default_contains_a_null_byte(): void
    {
        $table = new Table('users');
        $table->string('status', 40)->default("pending\0truncated");

        try {
            $this->create($table);

            self::fail('The grammar accepted a null byte in a default.');
        } catch (InvalidSchemaException $exception) {
            self::assertSame(['driver' => 'pgsql'], $exception->getContext());
        }
    }

    #[Test]
    public function it_compiles_a_unique_constraint(): void
    {
        $table = new Table('users');
        $table->string('email', 191)->unique();

        self::assertSame(
            [
                'CREATE TABLE "users" ("email" VARCHAR(191) NOT NULL, '
                    . 'CONSTRAINT "users_email_unique" UNIQUE ("email"))',
            ],
            $this->create($table),
        );
    }

    #[Test]
    public function it_compiles_a_foreign_key(): void
    {
        $table = new Table('users');
        $table->bigInteger('team_id');
        $table->foreign('team_id')->references('id')->on('teams')->onDelete(ReferentialAction::Cascade);

        self::assertSame(
            [
                'CREATE TABLE "users" ("team_id" BIGINT NOT NULL, '
                    . 'CONSTRAINT "users_team_id_foreign" FOREIGN KEY ("team_id") '
                    . 'REFERENCES "teams" ("id") ON DELETE CASCADE)',
            ],
            $this->create($table),
        );
    }

    #[Test]
    public function it_compiles_an_index_as_its_own_statement(): void
    {
        $table = new Table('users');
        $table->string('name');
        $table->index('name');

        self::assertSame(
            [
                'CREATE TABLE "users" ("name" VARCHAR(255) NOT NULL)',
                'CREATE INDEX "users_name_index" ON "users" ("name")',
            ],
            $this->create($table),
        );
    }

    #[Test]
    public function it_makes_the_index_conditional_when_the_create_is(): void
    {
        $table = new Table('users');
        $table->string('name');
        $table->index('name');

        self::assertSame(
            'CREATE INDEX IF NOT EXISTS "users_name_index" ON "users" ("name")',
            $this->create($table, true)[1],
        );
    }

    #[Test]
    public function it_leaves_the_index_unconditional_when_the_create_is_not(): void
    {
        $table = new Table('users');
        $table->string('name');
        $table->index('name');

        self::assertSame('CREATE INDEX "users_name_index" ON "users" ("name")', $this->create($table)[1]);
    }

    #[Test]
    public function it_compiles_a_drop(): void
    {
        self::assertSame(['DROP TABLE "users"'], $this->grammar->compileDrop('users', false)->queries);
    }

    #[Test]
    public function it_compiles_a_drop_if_exists(): void
    {
        self::assertSame(['DROP TABLE IF EXISTS "users"'], $this->grammar->compileDrop('users', true)->queries);
    }

    #[Test]
    public function it_compiles_a_rename(): void
    {
        self::assertSame(
            ['ALTER TABLE "users" RENAME TO "people"'],
            $this->grammar->compileRename('users', 'people')->queries,
        );
    }

    #[Test]
    public function it_compiles_a_has_table_query_scoped_to_the_current_schema(): void
    {
        self::assertSame(
            [
                'SELECT "table_name" FROM "information_schema"."tables" '
                    . 'WHERE "table_schema" = CURRENT_SCHEMA() AND "table_name" = \'users\'',
            ],
            $this->grammar->compileHasTable('users')->queries,
        );
    }

    #[Test]
    public function it_compiles_an_added_column(): void
    {
        $table = new Table('users');
        $table->string('phone', 40)->nullable();

        self::assertSame(['ALTER TABLE "users" ADD COLUMN "phone" VARCHAR(40) NULL'], $this->alter($table));
    }

    #[Test]
    public function it_compiles_a_dropped_column(): void
    {
        $table = new Table('users');
        $table->dropColumn('legacy');

        self::assertSame(['ALTER TABLE "users" DROP COLUMN "legacy"'], $this->alter($table));
    }

    #[Test]
    public function it_compiles_a_renamed_column(): void
    {
        $table = new Table('users');
        $table->renameColumn('name', 'full_name');

        self::assertSame(['ALTER TABLE "users" RENAME COLUMN "name" TO "full_name"'], $this->alter($table));
    }

    #[Test]
    public function it_modifies_a_column_with_one_action_per_property(): void
    {
        $table = new Table('users');
        $table->string('email', 320)->change();

        self::assertSame(
            [
                'ALTER TABLE "users" ALTER COLUMN "email" TYPE VARCHAR(320), '
                    . 'ALTER COLUMN "email" SET NOT NULL, ALTER COLUMN "email" DROP DEFAULT',
            ],
            $this->alter($table),
        );
    }

    #[Test]
    public function it_drops_not_null_and_sets_a_default_when_modifying(): void
    {
        $table = new Table('users');
        $table->string('email', 320)->nullable()->default('none')->change();

        self::assertSame(
            [
                'ALTER TABLE "users" ALTER COLUMN "email" TYPE VARCHAR(320), '
                    . 'ALTER COLUMN "email" DROP NOT NULL, ALTER COLUMN "email" SET DEFAULT \'none\'',
            ],
            $this->alter($table),
        );
    }

    #[Test]
    public function it_adds_a_constraint_to_an_existing_table(): void
    {
        $table = new Table('users');
        $table->unique('email');

        self::assertSame(
            ['ALTER TABLE "users" ADD CONSTRAINT "users_email_unique" UNIQUE ("email")'],
            $this->alter($table),
        );
    }

    #[Test]
    public function it_drops_a_constraint_from_an_existing_table(): void
    {
        $table = new Table('users');
        $table->dropConstraint('users_email_unique');

        self::assertSame(['ALTER TABLE "users" DROP CONSTRAINT "users_email_unique"'], $this->alter($table));
    }

    #[Test]
    public function it_drops_an_index_without_naming_the_table(): void
    {
        $table = new Table('users');
        $table->dropIndex('users_name_index');

        self::assertSame(['DROP INDEX "users_name_index"'], $this->alter($table));
    }
}
