<?php

declare(strict_types=1);

namespace Dirthara\Schema\Grammar;

use Dirthara\Schema\Identifier;
use Dirthara\Schema\Column\Column;
use Dirthara\Schema\Column\ColumnType;
use Dirthara\Schema\Sql\CompiledSchema;
use Dirthara\Schema\Constraint\PrimaryKey;
use Dirthara\Database\Connection\Driver\DriverName;

use function implode;
use function sprintf;
use function str_replace;

class PostgresSqlSchemaGrammar extends SqlSchemaGrammar
{
    public function compileHasTable(string $table): CompiledSchema
    {
        return new CompiledSchema([
            sprintf(
                'SELECT "table_name" FROM "information_schema"."tables" '
                . 'WHERE "table_schema" = CURRENT_SCHEMA() AND "table_name" = %s',
                $this->literal($this->identifier($table)->name),
            ),
        ]);
    }

    protected function driver(): DriverName
    {
        return DriverName::PostgresSql;
    }

    protected function wrap(Identifier $identifier): string
    {
        return '"' . str_replace('"', '""', $identifier->name) . '"';
    }

    protected function type(Column $column): string
    {
        return match ($column->type) {
            ColumnType::Boolean => 'BOOLEAN',
            ColumnType::TinyInteger, ColumnType::SmallInteger => 'SMALLINT',
            ColumnType::Integer => 'INTEGER',
            ColumnType::BigInteger => 'BIGINT',
            ColumnType::Decimal => sprintf('NUMERIC(%d, %d)', $column->precision ?? 8, $column->scale ?? 2),
            ColumnType::Float => 'REAL',
            ColumnType::Double => 'DOUBLE PRECISION',
            ColumnType::Char => sprintf('CHAR(%d)', $column->length ?? 255),
            ColumnType::String => sprintf('VARCHAR(%d)', $column->length ?? 255),
            ColumnType::Text => 'TEXT',
            ColumnType::Date => 'DATE',
            ColumnType::Time => 'TIME',
            ColumnType::DateTime, ColumnType::Timestamp => 'TIMESTAMP',
            ColumnType::Uuid => 'UUID',
            ColumnType::Json => 'JSONB',
            ColumnType::Binary => 'BYTEA',
        };
    }

    protected function inlinePrimaryKeyColumn(?PrimaryKey $primary, array $columns): ?Column
    {
        return null;
    }

    protected function unsigned(Column $column): string
    {
        return '';
    }

    protected function autoIncrement(Column $column, bool $inlinePrimaryKey): string
    {
        return $column->autoIncrement ? ' GENERATED BY DEFAULT AS IDENTITY' : '';
    }

    protected function boolean(bool $value): string
    {
        return $value ? 'TRUE' : 'FALSE';
    }

    protected function modifyColumn(Identifier $table, Column $column): string
    {
        $name = $this->wrap($column->name);

        $actions = [sprintf('ALTER COLUMN %s TYPE %s', $name, $this->type($column))];

        $actions[] = $column->nullable
            ? sprintf('ALTER COLUMN %s DROP NOT NULL', $name)
            : sprintf('ALTER COLUMN %s SET NOT NULL', $name);

        $actions[] = $column->hasDefault
            ? sprintf('ALTER COLUMN %s SET DEFAULT %s', $name, $this->literal($column->default))
            : sprintf('ALTER COLUMN %s DROP DEFAULT', $name);

        return sprintf('ALTER TABLE %s %s', $this->wrap($table), implode(', ', $actions));
    }

    protected function dropIndex(Identifier $table, Identifier $index): string
    {
        return sprintf('DROP INDEX %s', $this->wrap($index));
    }
}
